{
 "title": "Keycloak",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(jvm_memory_bytes_used{service=\"sso\"}, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Registrations",
   "type": "singlestat",
   "description": "All registered users in the application.",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(keycloak_registrations{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Total Logins",
   "type": "singlestat",
   "description": "All occurred log in events. This does not show current active users.",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(keycloak_logins{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Total Login Errors",
   "type": "singlestat",
   "description": "All failed login attempts that have occurred.",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(keycloak_failed_login_attempts{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Current Memory",
   "type": "singlestat",
   "description": "Memory currently being used by Keycloak.",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(jvm_memory_bytes_used{area=\"heap\",namespace=\"$namespace\", service=\"sso\"}) + max(jvm_memory_bytes_used{area=\"nonheap\", namespace=\"$namespace\", service=\"sso\"})"
    }
   ]
  },
  {
   "title": "Logins",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "keycloak_logins{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Login Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "keycloak_failed_login_attempts{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_max{namespace=\"$namespace\",service=\"sso\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{namespace=\"$namespace\",service=\"sso\"})",
     "legendFormat": "Comitted"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{namespace=\"$namespace\",service=\"sso\"})",
     "legendFormat": "Used"
    }
   ]
  }
 ]
}